version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17 #updating to java 17
  pre_build:
    commands:
      - yum update -y
      - yum install -y jq
      - wget https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar xzf apache-maven-3.9.6-bin.tar.gz
      - ln -s apache-maven-3.9.6 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip ./sonar-scanner-cli-5.0.1.3006-linux.zip
      - export PATH=$PATH:/sonar-scanner-5.0.1.3006-linux/bin/

  build:
    commands:
      - sonar-scanner-5.0.1.3006-linux/bin/sonar-scanner -Dsonar.login=$TOKEN -Dsonar.host.url=$HOST -Dsonar.projectKey=$PROJECT -Dsonar.organization=$ORGANIZATION -Dsonar.python.version=3 -Dsonar.python.coverage.reportPaths=coverage.xml
      - wget "https://sonarcloud.io/api/qualitygates/project_status?projectKey={{$Project}}" > result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
