version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17 #updating to java 17
  pre_build:
    commands:
      - yum update -y
      - yum install -y jq
      - wget https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar xzf apache-maven-3.9.6-bin.tar.gz
      - ln -s apache-maven-3.9.6 maven
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.3.0.1492-linux.zip
      - unzip ./sonar-scanner-cli-3.3.0.1492-linux.zip
      - mv sonar-scanner-3.3.0.1492-linux /sonar-scanner
      - export PATH=$PATH:/sonar-scanner/bin/

  build:
    commands:
      - sonar-scanner -Dsonar.login=c5a367dded8439edcd8a88576e2f9615a62206bf -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=Utkarsh-NCI_x22229698-devops -Dsonar.organization=utkarsh-nci -Dsonar.python.version=3
      - sleep 5
      - if curl -s -o /dev/null -w "%{http_code}" https://sonarcloud.io/api/qualitygates/project_status?projectKey=Utkarsh-NCI_x22229698-devops != "200"; then exit 1; fi
