# Generated by Django 4.2.11 on 2024-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_topic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
