# Generated by Django 4.2.11 on 2024-03-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_module_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
