# Generated by Django 4.2.11 on 2024-03-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0004_module_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='module',
        ),
        migrations.AddField(
            model_name='module',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.topic'),
        ),
    ]
