# Generated by Django 4.2.11 on 2024-03-29 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_rename_topic_module_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='modules.module'),
        ),
    ]
